import os
IMAGE_FILE_EXTENSION = ".png"
FONT_FILE_EXTENSION = ".otf"

'''Paths'''
RESOURCES_FOLDER_BASE_PATH = os.path.dirname(os.path.dirname(__file__))
IMAGE_FOLDER_IMAGES_PATH = RESOURCES_FOLDER_BASE_PATH + r"\images"
IMAGE_FOLDER_FONTS_PATH = RESOURCES_FOLDER_BASE_PATH + r"\fonts"

IMAGE_FOLDER_ENCYCLOPEDIA_PATH = IMAGE_FOLDER_IMAGES_PATH + r"\encyclopedia_resources"
IMAGE_FOLDER_DEX_ICON_PATH = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\dex_icons"
IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\top_bar"
IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\bottom_bar"


'''Font Files'''
FONT_FOREST_BOLD_FILE_TEMP = IMAGE_FOLDER_FONTS_PATH + r"\NationalForestPrintBold" + FONT_FILE_EXTENSION
FONT_FOREST_REGULAR_FILE = IMAGE_FOLDER_FONTS_PATH + r"\NationalForestPrintRegular" + FONT_FILE_EXTENSION


'''DEX ICON FILES'''
DEX_ICON_BASE = IMAGE_FOLDER_DEX_ICON_PATH + r"\DexIcon"
DEX_ICON_BACKGROUND_BASE = DEX_ICON_BASE + "_BackgroundColor"
DEX_ICON_CREATURE_BASE = DEX_ICON_BASE + "_Creature"

DEX_ICON_CREATURE_LOCKED_ICON_IMAGE = DEX_ICON_CREATURE_BASE + "_LockedIcon" + IMAGE_FILE_EXTENSION
DEX_ICON_SHADOW_IMAGE = DEX_ICON_BASE + "_BGShadow" + IMAGE_FILE_EXTENSION
DEX_ICON_STATS_BAR_IMAGE = DEX_ICON_BASE + "_StatsBar" + IMAGE_FILE_EXTENSION
DEX_ICON_OVERLAY = DEX_ICON_BASE + "_Overlay" + IMAGE_FILE_EXTENSION


'''ENCOUNTER SCREEN IMAGES'''
TEXT_BOX_IMAGE = IMAGE_FOLDER_IMAGES_PATH + r"\env_textbox" + IMAGE_FILE_EXTENSION


'''ENCYCLOPEDIA IMAGES'''
ENCYCLOPEDIA_CORNER_OVERLAY_BASE = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\EncyclopediaPage_CornerOverlay"
ENCYCLOPEDIA_BG_BASE = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\EncyclopediaPage_BG"

ENCYCLOPEDIA_OVERLAY_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\EncyclopediaPage_Overlay"
ENCYCLOPEDIA_CORNER_OVERLAY_SERVER_IMAGE = ENCYCLOPEDIA_CORNER_OVERLAY_BASE + r"_CornerOverlay_Server" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_CORNER_OVERLAY_USER_IMAGE = ENCYCLOPEDIA_CORNER_OVERLAY_BASE + r"_CornerOverlay_User" + IMAGE_FILE_EXTENSION

ENCYCLOPEDIA_BG_FOREST_1 = ENCYCLOPEDIA_BG_BASE + r"_BG_1" + IMAGE_FILE_EXTENSION


'''CREATURE IMAGES'''
CREATURE_IMAGE_ENCOUNTER_EXTENSION = "_E"
CREATURE_IMAGE_FLEE_EXTENSION = "_F"
CREATURE_IMAGE_CATCH_EXTENSION = "_C"
CREATURE_IMAGE_THUMBNAIL_EXTENSION = "_THUMB"

CREATURE_IMAGE_CHIPMUNK_ROOT = "Chipmunk"
CREATURE_IMAGE_DEER_ROOT = "Deer"




'''EXTERNAL IMAGES'''
'''EMBED ICONS'''
TGOMMO_CREATURE_EMBED_GRASS_ICON = "https://i.pinimg.com/originals/22/13/5b/22135b26441d0e9163eb4445af0c56c2.gif"
TGOMMO_CREATURE_EMBED_LOCATION_ICON = "https://cdn-icons-png.flaticon.com/512/535/535137.png"