import os

""" ----- PROJECT DIRECTORY PATHS  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "output")
LOGS_DIR = os.path.join(PROJECT_ROOT, "logs")

SRC_ROOT = os.path.join(PROJECT_ROOT, "src")
RESOURCES_FOLDER_BASE_PATH = os.path.join(SRC_ROOT, "resources")



""" ----- SUPPORT FUNCTIONS & VARIABLES---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
IMAGE_FILE_EXTENSION = ".png"
FONT_FILE_EXTENSION = ".otf"

""" ----- IMAGES  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
""" ----- FOLDER PATHS  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
# region IMAGE FOLDER PATHS
IMAGE_FOLDER_IMAGES_PATH = os.path.join(RESOURCES_FOLDER_BASE_PATH, "images")

# region Object Paths
# region Creatures Paths
IMAGE_FOLDER_CREATURES_PATH = os.path.join(IMAGE_FOLDER_IMAGES_PATH, "creatures")
IMAGE_FOLDER_CREATURE_THUMBNAILS_PATH = os.path.join(IMAGE_FOLDER_CREATURES_PATH, "thumbnails")
IMAGE_FOLDER_CREATURE_ICONS_PATH = os.path.join(IMAGE_FOLDER_CREATURES_PATH, "icons")
# endregion
# region Environments Paths
IMAGE_FOLDER_ENVIRONMENTS_PATH = os.path.join(IMAGE_FOLDER_IMAGES_PATH, "environments")
FALLBACK_ENVIRONMENT_PATH = os.path.join(IMAGE_FOLDER_ENVIRONMENTS_PATH, "default")
# endregion
# region Avatars Paths
IMAGE_FOLDER_AVATARS_PATH = os.path.join(IMAGE_FOLDER_IMAGES_PATH, "avatars")

IMAGE_FOLDER_AVATAR_ICONS_PATH = os.path.join(IMAGE_FOLDER_AVATARS_PATH, "avatar_icons")
IMAGE_FOLDER_AVATAR_THUMBNAILS_PATH = os.path.join(IMAGE_FOLDER_AVATARS_PATH, "avatar_thumbnails")
IMAGE_FOLDER_AVATAR_QUESTS_PATH = os.path.join(IMAGE_FOLDER_AVATARS_PATH, "avatar_quests")
# endregion
# region Item Paths
IMAGE_FOLDER_ITEMS_PATH = os.path.join(IMAGE_FOLDER_IMAGES_PATH, "items")
# endregion
# endregion

# region Game Feature Paths
IMAGE_FOLDER_GAME_FEATURES_PATH = os.path.join(IMAGE_FOLDER_IMAGES_PATH, "game_features")
# region Encounter Screen Paths
# endregion
# region Travel Advisory Paths
IMAGE_FOLDER_TRAVEL_ADVISORY_PATH = os.path.join(IMAGE_FOLDER_ENVIRONMENTS_PATH, "travel_advisories")
# endregion

# region Encyclopedia paths
IMAGE_FOLDER_ENCYCLOPEDIA_PATH = os.path.join(IMAGE_FOLDER_GAME_FEATURES_PATH, "encyclopedia")
IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_PATH, "top_bar")
IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_PATH, "bottom_bar")
IMAGE_FOLDER_ENCYCLOPEDIA_XL_PATH = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_PATH, "encyclopedia_xl")
# endregion
# region Encyclopedia Location Index paths
IMAGE_FOLDER_ENCYCLOPEDIA_LOCATION_INDEX_PATH = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_PATH, "location_tab")
IMAGE_FOLDER_ENCYCLOPEDIA_LOCATION_INDEX_ENVIRONMENT_BG_PATH = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_LOCATION_INDEX_PATH, "environment_bgs")
# endregion

# region Player Profile Paths
IMAGE_FOLDER_PLAYER_PROFILE_PATH = os.path.join(IMAGE_FOLDER_GAME_FEATURES_PATH, "player_profile_images")

IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_PATH = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_PATH, "side_panel")
IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_TABS_PATH = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_PATH, "tabs")
IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_TEAM_TABS_PATH = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_PATH, "team_tabs")
IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_ENVIRONMENT_TABS_PATH = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_PATH, "environment_tabs")
IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_COLLECTIONS_TABS_PATH = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_PATH, "collections_tabs")
# endregion

# region Avatar Board paths
IMAGE_FOLDER_AVATAR_BOARD_PATH = os.path.join(IMAGE_FOLDER_GAME_FEATURES_PATH, "avatar_board")
# endregion
# region Creature Inventory Paths
IMAGE_FOLDER_CREATURE_INVENTORY_PATH = os.path.join(IMAGE_FOLDER_GAME_FEATURES_PATH, "creature_inventory")
IMAGE_FOLDER_CREATURE_INVENTORY_RELEASE_SUMMARY_PATH = os.path.join(IMAGE_FOLDER_CREATURE_INVENTORY_PATH, "release_summary")
# endregion
# region Item Inventory Paths
IMAGE_FOLDER_ITEM_INVENTORY_PATH = os.path.join(IMAGE_FOLDER_GAME_FEATURES_PATH, "item_inventory")
IMAGE_FOLDER_ITEM_INVENTORY_ICON_PATH = os.path.join(IMAGE_FOLDER_ITEM_INVENTORY_PATH, "icons")
# endregion

# region Shop Paths
IMAGE_FOLDER_SHOP_BOARD_PATH = os.path.join(IMAGE_FOLDER_GAME_FEATURES_PATH, "shop")
# endregion

# region Trap Manager Paths
IMAGE_FOLDER_TRAP_MANAGER_PATH = os.path.join(IMAGE_FOLDER_GAME_FEATURES_PATH, "trap_manager")
IMAGE_FOLDER_TRAP_MANAGER_SUMMARY_MENU_PATH = os.path.join(IMAGE_FOLDER_TRAP_MANAGER_PATH, "summary_menu")
IMAGE_FOLDER_TRAP_MANAGER_CAPTURE_MENU_PATH = os.path.join(IMAGE_FOLDER_TRAP_MANAGER_PATH, "capture_menu")
IMAGE_FOLDER_TRAP_MANAGER_FOREGROUND_DECORATION_PATH = os.path.join(IMAGE_FOLDER_TRAP_MANAGER_PATH, "foreground_trap_decoration")
# endregion

# endregion

# region Misc Paths
# region Help Image Paths
IMAGE_FOLDER_HELP_IMAGE_PATH = os.path.join(IMAGE_FOLDER_IMAGES_PATH, "help_images")
# endregion
# endregion
# endregion

""" ----- IMAGE ROOTS  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
# region Object Image Roots
# region Creature Image Roots
# endregion
# region Environment Image Roots
# endregion
# region Avatar Image Roots
PLAYER_PROFILE_AVATAR_BASE = os.path.join(IMAGE_FOLDER_AVATAR_THUMBNAILS_PATH, "UserProfile_Avatar")
AVATAR_QUEST_BASE = os.path.join(IMAGE_FOLDER_AVATAR_QUESTS_PATH, "QuestTab_IndividualQuest")
# endregion
# region Items Image Roots
ITEM_BASE = os.path.join(IMAGE_FOLDER_ITEMS_PATH, "item_")
# endregion
# endregion

# region Game Features Roots
# region Encounter Screen Roots
ENCOUNTER_SCREEN_ENVIRONMENT_BG_PREFIX = "EncounterScreen_BG_"

ENCOUNTER_SCREEN_BASE = os.path.join(IMAGE_FOLDER_ENVIRONMENTS_PATH, "EncounterScreen_")
ENCOUNTER_SCREEN_ENVIRONMENT_BG_BASE = ENCOUNTER_SCREEN_BASE + "BG_"
ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE = ENCOUNTER_SCREEN_BASE + "GLOW_"

ENCOUNTER_SCREEN_OVERLAY_SUFFIX = "_overlay"
ENCOUNTER_SCREEN_THUMBNAIL_SUFFIX = "_THUMB" + IMAGE_FILE_EXTENSION
# endregion
# region Travel Advisory Roots
TGOMMO_TRAVEL_ADVISORY_BASE = os.path.join(IMAGE_FOLDER_TRAVEL_ADVISORY_PATH, "travel_advisory_")
TGOMMO_TRAVEL_ADVISORY_LANDING_BASE = TGOMMO_TRAVEL_ADVISORY_BASE + "landed_"
# endregion

# region Encyclopedia Roots
ENCYCLOPEDIA_IMAGE_FILENAME_PREFIX = "EncyclopediaPage"
ENCYCLOPEDIA_OVERLAY_BASE = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_PATH, ENCYCLOPEDIA_IMAGE_FILENAME_PREFIX)

ENCYCLOPEDIA_TOP_BAR_IMAGE_BASE = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH, f"{ENCYCLOPEDIA_IMAGE_FILENAME_PREFIX}_TopBar")

ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH, f"{ENCYCLOPEDIA_IMAGE_FILENAME_PREFIX}_BottomBar")

ENCYCLOPEDIA_XL_IMAGE_BASE = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_XL_PATH, f"{ENCYCLOPEDIA_IMAGE_FILENAME_PREFIX}XL")
ENCYCLOPEDIA_XL_BOX_BASE = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_XL_PATH, "EncyclopediaPageXL_Box_")
# endregion
# region Encyclopedia Location Index Roots
ENCYCLOPEDIA_LOCATION_INDEX_ITAB_FILENAME_PREFIX = f"{ENCYCLOPEDIA_IMAGE_FILENAME_PREFIX}_LocationTab"
ENCYCLOPEDIA_LOCATION_INDEX_IMAGE_BASE = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_LOCATION_INDEX_PATH, ENCYCLOPEDIA_LOCATION_INDEX_ITAB_FILENAME_PREFIX)
ENCYCLOPEDIA_LOCATION_INDEX_ENVIRONMENT_BG_IMAGE_BASE = os.path.join(IMAGE_FOLDER_ENCYCLOPEDIA_LOCATION_INDEX_ENVIRONMENT_BG_PATH, f"{ENCYCLOPEDIA_LOCATION_INDEX_ITAB_FILENAME_PREFIX}_Environment")
# endregion
# region Encyclopedia Dex Icon Roots
DEX_ICON_BASE = os.path.join(IMAGE_FOLDER_CREATURE_ICONS_PATH, "DexIcon")
DEX_ICON_BACKGROUND_BASE = DEX_ICON_BASE + "_BackgroundColor"
DEX_ICON_CREATURE_BASE = DEX_ICON_BASE + "_Creature"
# endregion

# region Player Profile Roots
PLAYER_PROFILE_BASE = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_PATH, "UserProfile")
PLAYER_PROFILE_SIDE_PANEL_BASE = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_PATH, "UserProfile_SidePanel")
PLAYER_PROFILE_SIDE_PANEL_OVERLAY_BASE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_Overlay"
PLAYER_PROFILE_BACKGROUND_BASE = PLAYER_PROFILE_BASE + "_BG"
# endregion

# region Avatar Board Roots
AVATAR_BOARD_IMAGE_BASE = os.path.join(IMAGE_FOLDER_AVATAR_BOARD_PATH, "AvatarBoard")
AVATAR_BOARD_BUTTON_BASE = AVATAR_BOARD_IMAGE_BASE + "_Button"
AVATAR_QUEST_TAB_BASE = os.path.join(IMAGE_FOLDER_AVATAR_BOARD_PATH, "QuestTab")

AVATAR_BOARD_UNLOCKED_AVATAR_BASE = os.path.join(IMAGE_FOLDER_AVATAR_ICONS_PATH, "AvatarBoard_UnlockedAvatar")
AVATAR_BOARD_UNLOCKED_AVATAR_THUMBNAIL_BASE = AVATAR_BOARD_UNLOCKED_AVATAR_BASE + "_THUMB"
AVATAR_BOARD_UNLOCKED_AVATAR_BACKGROUND_BASE = AVATAR_BOARD_UNLOCKED_AVATAR_BASE + "_Background"
# endregion
# region Creature Inventory Roots
CREATURE_INVENTORY_IMAGE_BASE = os.path.join(IMAGE_FOLDER_CREATURE_INVENTORY_PATH, "CreatureInventory")
CREATURE_INVENTORY_INDIVIDUAL_CREATURE_TAB_BASE = CREATURE_INVENTORY_IMAGE_BASE + "_IndividualCreatureTab"
CREATURE_INVENTORY_RELEASE_SUMMARY_BASE = os.path.join(IMAGE_FOLDER_CREATURE_INVENTORY_RELEASE_SUMMARY_PATH, "CreatureInventory_ReleaseSummary")

CREATURE_INVENTORY_INDIVIDUAL_CREATURE_FAVORITE_STAMP_BASE = CREATURE_INVENTORY_INDIVIDUAL_CREATURE_TAB_BASE + "_Stamp"
# endregion
# region Item Inventory Roots
ITEM_INVENTORY_BASE = os.path.join(IMAGE_FOLDER_ITEM_INVENTORY_PATH, "ItemInventory_")
ITEM_INVENTORY_ICON_BASE = os.path.join(IMAGE_FOLDER_ITEM_INVENTORY_ICON_PATH, "ItemInventory_Icon_")

# endregion

# region Shop Roots
SHOP_BASE = os.path.join(IMAGE_FOLDER_SHOP_BOARD_PATH, "Shop")
SHOP_SHELF_BASE = SHOP_BASE + "_Shelf"
SHOP_ITEM_CASE_BASE = SHOP_BASE + "_ItemCase"
SHOP_UPDATE_BASE = SHOP_BASE + "_Update"
# endregion

# region Trap Manager Roots
TRAP_MANAGER_BASE = os.path.join(IMAGE_FOLDER_TRAP_MANAGER_PATH, "TrapManager")
TRAP_MANAGER_OVERLAY_BASE = TRAP_MANAGER_BASE + "_Overlay"

TRAP_MANAGER_OVERLAY_SUMMARY_BASE = TRAP_MANAGER_OVERLAY_BASE + "_Summary"
TRAP_MANAGER_OVERLAY_SUMMARY_TRAP_MODE_BASE = TRAP_MANAGER_OVERLAY_SUMMARY_BASE + "_TrapMode"
TRAP_MANAGER_OVERLAY_SUMMARY_BATTERY_BASE = TRAP_MANAGER_OVERLAY_SUMMARY_BASE + "_Battery"

TRAP_MANAGER_OVERLAY_CAPTURES_BASE = TRAP_MANAGER_OVERLAY_BASE + "_Captures"

TRAP_MANAGER_FOREGROUND_TREE_BASE = os.path.join(IMAGE_FOLDER_TRAP_MANAGER_FOREGROUND_DECORATION_PATH, "TrapManager_ForegroundTrap")
# endregion

# endregion

""" ----- STATIC IMAGES  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
# region Object Images
# region Creature Images
FALLBACK_CREATURE_IMAGE = os.path.join(IMAGE_FOLDER_CREATURE_THUMBNAILS_PATH, "NA_THUMB" + IMAGE_FILE_EXTENSION)
FALLBACK_CREATURE_DEX_ICON_IMAGE = os.path.join(IMAGE_FOLDER_CREATURE_ICONS_PATH, "DexIcon_Creature_NA" + IMAGE_FILE_EXTENSION)
# endregion
# region Environment Images
# endregion
# region Avatar Images
AVATAR_FALLBACK_1_IMAGE = PLAYER_PROFILE_AVATAR_BASE + "Fallback_1" + IMAGE_FILE_EXTENSION
AVATAR_FALLBACK_2_IMAGE = PLAYER_PROFILE_AVATAR_BASE + "Fallback_2" + IMAGE_FILE_EXTENSION
UNLOCKED_AVATAR_BACKGROUND_IMAGE = os.path.join(IMAGE_FOLDER_AVATARS_PATH, "AvatarUnlocked_BG" + IMAGE_FILE_EXTENSION)
# endregion
# region Items Images
# endregion
# endregion

# region Game Features Images
# region Encounter Screen Images
ENCOUNTER_SCREEN_CAMERA_OVERLAY_IMAGE = ENCOUNTER_SCREEN_BASE + "Camera_Overlay" + IMAGE_FILE_EXTENSION
ENCOUNTER_SCREEN_TEXT_BOX_IMAGE = ENCOUNTER_SCREEN_BASE + "textbox" + IMAGE_FILE_EXTENSION

ENCOUNTER_SCREEN_NIGHT_GLOW_IMAGE = ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE + "night" + IMAGE_FILE_EXTENSION
ENCOUNTER_SCREEN_EVENING_GLOW_IMAGE = ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE + "evening" + IMAGE_FILE_EXTENSION
ENCOUNTER_SCREEN_MORNING_GLOW_IMAGE = ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE + "morning" + IMAGE_FILE_EXTENSION
ENCOUNTER_SCREEN_EVENING_RAYS_IMAGE = ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE + "evening_rays" + IMAGE_FILE_EXTENSION
ENCOUNTER_SCREEN_MORNING_RAYS_IMAGE = ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE + "morning_rays" + IMAGE_FILE_EXTENSION
ENCOUNTER_SCREEN_TRANSCENDANT_GLOW_IMAGE = ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE + "transcendant" + IMAGE_FILE_EXTENSION
ENCOUNTER_SCREEN_EVENT_HALLOWEEN_GLOW_IMAGE = ENCOUNTER_SCREEN_ENVIRONMENT_GLOW_BASE + "Pumpkin" + IMAGE_FILE_EXTENSION
# endregion
# region Travel Advisory Images
# endregion

# region Encyclopedia Images
ENCYCLOPEDIA_OVERLAY_IMAGE = ENCYCLOPEDIA_OVERLAY_BASE + "_Overlay" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_OVERLAY_SHINY_IMAGE = ENCYCLOPEDIA_OVERLAY_BASE + "_Overlay_SHINY" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_OVERLAY_NIGHT_IMAGE = ENCYCLOPEDIA_OVERLAY_BASE + "_Overlay_NIGHT" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_OVERLAY_DAY_IMAGE = ENCYCLOPEDIA_OVERLAY_BASE + "_Overlay_DAY" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TEXT_SHADOW_IMAGE = ENCYCLOPEDIA_OVERLAY_BASE + "_Blackbar" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_CORNER_OVERLAY_SERVER_IMAGE = ENCYCLOPEDIA_OVERLAY_BASE + "_CornerOverlay_Server" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_CORNER_OVERLAY_USER_IMAGE = ENCYCLOPEDIA_OVERLAY_BASE + "_CornerOverlay_User" + IMAGE_FILE_EXTENSION

ENCYCLOPEDIA_TOP_BAR_DEFAULT_IMAGE = ENCYCLOPEDIA_TOP_BAR_IMAGE_BASE + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_SHINY_IMAGE = ENCYCLOPEDIA_TOP_BAR_IMAGE_BASE + "_Shiny" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_NIGHT_IMAGE = ENCYCLOPEDIA_TOP_BAR_IMAGE_BASE + "_Night" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_DAY_IMAGE = ENCYCLOPEDIA_TOP_BAR_IMAGE_BASE + "_Day" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_CAMERA_ICON_IMAGE = ENCYCLOPEDIA_TOP_BAR_IMAGE_BASE + "_CameraIcon" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_ENCOUNTER_ICON_IMAGE = ENCYCLOPEDIA_TOP_BAR_IMAGE_BASE + "_EncounterIcon" + IMAGE_FILE_EXTENSION

ENCYCLOPEDIA_BOTTOM_BAR_DEFAULT_IMAGE = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BAR_SHINY_IMAGE = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_Shiny" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BAR_NIGHT_IMAGE = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_Night" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BAR_DAY_IMAGE = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_Day" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BACK_ARROW_IMAGE = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_Arrow_Backward" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_FORWARD_ARROW_IMAGE = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_Arrow_Forward" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BACK_ARROW_IMAGE_DISABLED = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_Arrow_Backward_Disabled" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_FORWARD_ARROW_IMAGE_DISABLED = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_Arrow_Forward_Disabled" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_ENVIRONMENT_ICON_IMAGE = ENCYCLOPEDIA_BOTTOM_BAR_IMAGE_BASE + "_EnvironmentIcon" + IMAGE_FILE_EXTENSION

ENCYCLOPEDIA_XL_OVERLAY_IMAGE = ENCYCLOPEDIA_XL_IMAGE_BASE + "_Overlay" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_XL_BACKGROUND_IMAGE = ENCYCLOPEDIA_XL_IMAGE_BASE + "_Background" + IMAGE_FILE_EXTENSION
# endregion
# region Encyclopedia Location Index images
ENCYCLOPEDIA_LOCATION_INDEX_OVERLAY_IMAGE = ENCYCLOPEDIA_LOCATION_INDEX_IMAGE_BASE + "_Overlay" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_LOCATION_INDEX_EMPTY_STARS_IMAGE = ENCYCLOPEDIA_LOCATION_INDEX_IMAGE_BASE + "_EmptyStars" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_LOCATION_INDEX_STAR_1_MAGE = ENCYCLOPEDIA_LOCATION_INDEX_IMAGE_BASE + "_Star1" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_LOCATION_INDEX_STAR_2_MAGE = ENCYCLOPEDIA_LOCATION_INDEX_IMAGE_BASE + "_Star2" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_LOCATION_INDEX_STAR_3_MAGE = ENCYCLOPEDIA_LOCATION_INDEX_IMAGE_BASE + "_Star3" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_LOCATION_INDEX_CORKBOARD_MAGE = ENCYCLOPEDIA_LOCATION_INDEX_IMAGE_BASE + "_Corkboard" + IMAGE_FILE_EXTENSION
# endregion
# region Encyclopedia Dex Icon Images
DEX_ICON_CREATURE_LOCKED_ICON_IMAGE = DEX_ICON_CREATURE_BASE + "_LockedIcon" + IMAGE_FILE_EXTENSION
DEX_ICON_SHADOW_IMAGE = DEX_ICON_BASE + "_BGShadow" + IMAGE_FILE_EXTENSION
DEX_ICON_STATS_BAR_IMAGE = DEX_ICON_BASE + "_StatsBar" + IMAGE_FILE_EXTENSION
DEX_ICON_OVERLAY = DEX_ICON_BASE + "_Overlay" + IMAGE_FILE_EXTENSION
DEX_ICON_TRANSCENDANT_OVERLAY = DEX_ICON_BASE + "_Transcendant_Overlay" + IMAGE_FILE_EXTENSION
# endregion

# region Player Profile images
PLAYER_PROFILE_DIRT_PATCHES_IMAGE = PLAYER_PROFILE_BASE + "_DirtPatches" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_TOP_BAR_IMAGE = PLAYER_PROFILE_BASE + "_TopBar" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_CLOSED_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_Closed" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_OPEN_BORDER_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_Open_Border" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_OPEN_BORDER_BACKGROUND_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_Open_Border_Background" + IMAGE_FILE_EXTENSION

PLAYER_PROFILE_SIDE_PANEL_DOWN_BUTTON_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_DownButton" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_UP_BUTTON_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_UpButton" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_LEFT_BUTTON_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_LeftButton" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_RIGHT_BUTTON_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_RightButton" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_LEFT_BUTTON_DISABLED_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_LeftButton_Disabled" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_RIGHT_BUTTON_DISABLED_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_RightButton_Disabled" + IMAGE_FILE_EXTENSION

PLAYER_PROFILE_SIDE_PANEL_TEAM_OVERLAY_IMAGE = PLAYER_PROFILE_SIDE_PANEL_OVERLAY_BASE + "_Team" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_BIOMES_OVERLAY_IMAGE = PLAYER_PROFILE_SIDE_PANEL_OVERLAY_BASE + "_Biomes" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_COLLECTIONS_OVERLAY_IMAGE = PLAYER_PROFILE_SIDE_PANEL_OVERLAY_BASE + "_Collections" + IMAGE_FILE_EXTENSION

PLAYER_PROFILE_SIDE_PANEL_OPEN_BORDER_BACKGROUND_01_IMAGE = PLAYER_PROFILE_SIDE_PANEL_BASE + "_Open_Border_Background"
# endregion
# region Player Profile Tab images
PLAYER_PROFILE_SIDE_PANEL_TABS_IMAGE_BASE = os.path.join(IMAGE_FOLDER_PLAYER_PROFILE_SIDE_PANEL_TABS_PATH, "UserProfile_SidePanel_Tabs")
PLAYER_PROFILE_SIDE_PANEL_TABS_BACKGROUND_IMAGE_BASE = PLAYER_PROFILE_SIDE_PANEL_TABS_IMAGE_BASE + "_BG"
PLAYER_PROFILE_SIDE_PANEL_TABS_STARS_IMAGE_BASE = PLAYER_PROFILE_SIDE_PANEL_TABS_IMAGE_BASE + "_Stars"
PLAYER_PROFILE_SIDE_PANEL_ENVIRONMENT_IMAGE_BASE = PLAYER_PROFILE_SIDE_PANEL_TABS_IMAGE_BASE + "_Environment"

PLAYER_PROFILE_SIDE_PANEL_TABS_OVERLAY_IMAGE = PLAYER_PROFILE_SIDE_PANEL_TABS_IMAGE_BASE + "_Overlay" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_TABS_OVERLAY_SHADOW_IMAGE = PLAYER_PROFILE_SIDE_PANEL_TABS_IMAGE_BASE + "_Overlay_Shadow" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_TABS_BG_SHADOW_IMAGE = PLAYER_PROFILE_SIDE_PANEL_TABS_BACKGROUND_IMAGE_BASE + "_Shadow" + IMAGE_FILE_EXTENSION
PLAYER_PROFILE_SIDE_PANEL_TABS_EMPTY_STARS_IMAGE = PLAYER_PROFILE_SIDE_PANEL_TABS_STARS_IMAGE_BASE + "_Blank" + IMAGE_FILE_EXTENSION
# endregion

# region Avatar Board images
AVATAR_BOARD_BACKGROUND_IMAGE = AVATAR_BOARD_IMAGE_BASE + "_Background" + IMAGE_FILE_EXTENSION
AVATAR_BOARD_CORNER_OVERLAY = AVATAR_BOARD_IMAGE_BASE + "_CornerOverlay_AvatarBoard" + IMAGE_FILE_EXTENSION
AVATAR_BOARD_BUTTON_AVATAR_QUESTS_INACTIVE_IMAGE = AVATAR_BOARD_BUTTON_BASE + "_AvatarQuests_Inactive" + IMAGE_FILE_EXTENSION
AVATAR_BOARD_BUTTON_AVATAR_QUESTS_ACTIVE_IMAGE = AVATAR_BOARD_BUTTON_BASE + "_AvatarQuests_Active" + IMAGE_FILE_EXTENSION
AVATAR_BOARD_BUTTON_UNLOCKED_AVATAR_INACTIVE_IMAGE = AVATAR_BOARD_BUTTON_BASE + "_UnlockedAvatars_Inactive" + IMAGE_FILE_EXTENSION
AVATAR_BOARD_BUTTON_UNLOCKED_AVATAR_ACTIVE_IMAGE = AVATAR_BOARD_BUTTON_BASE + "_UnlockedAvatars_Active" + IMAGE_FILE_EXTENSION

AVATAR_UNLOCKED_AVATAR_TAB_BORDER_IMAGE = AVATAR_BOARD_IMAGE_BASE + "_UnlockedAvatar_WhiteBorder" + IMAGE_FILE_EXTENSION

AVATAR_QUEST_TAB_WHITE_BORDER_IMAGE = AVATAR_QUEST_TAB_BASE + "_WhiteBorder" + IMAGE_FILE_EXTENSION
AVATAR_QUEST_TAB_GREEN_BORDER_IMAGE = AVATAR_QUEST_TAB_BASE + "_GreenBorder" + IMAGE_FILE_EXTENSION
AVATAR_QUEST_TAB_COMPLETE_TEXT_IMAGE = AVATAR_QUEST_TAB_BASE + "_CompleteText" + IMAGE_FILE_EXTENSION
AVATAR_QUEST_TAB_PROGRESS_TAB_IMAGE = AVATAR_QUEST_TAB_BASE + "_ProgressTab" + IMAGE_FILE_EXTENSION
# endregion
# region Creature Inventory images
CREATURE_INVENTORY_BG_IMAGE = CREATURE_INVENTORY_IMAGE_BASE + "_BG" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_BG_RELEASE_IMAGE = CREATURE_INVENTORY_IMAGE_BASE + "_BG_Release" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_CORNER_OVERLAY_IMAGE = CREATURE_INVENTORY_IMAGE_BASE + "_CornerOverlay" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_BOX_ICON = CREATURE_INVENTORY_IMAGE_BASE + "_BoxIcon" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_BOX_ICON_SELECTED = CREATURE_INVENTORY_IMAGE_BASE + "_BoxIcon_Selected" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_BOX_ICON_LOCKED = CREATURE_INVENTORY_IMAGE_BASE + "_BoxIcon_Locked" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_MENU_OVERLAY_IMAGE = CREATURE_INVENTORY_IMAGE_BASE + "_Menu" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_MENU_RELEASE_OVERLAY_IMAGE = CREATURE_INVENTORY_IMAGE_BASE + "_Menu_Release" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_MENU_FAVORITE_OVERLAY_IMAGE = CREATURE_INVENTORY_IMAGE_BASE + "_Menu_Favorite" + IMAGE_FILE_EXTENSION

CREATURE_INVENTORY_INDIVIDUAL_CREATURE_TAB_WHITE_BORDER_IMAGE = CREATURE_INVENTORY_INDIVIDUAL_CREATURE_TAB_BASE + "_Overlay" + IMAGE_FILE_EXTENSION

CREATURE_INVENTORY_INDIVIDUAL_CREATURE_FAVORITE_STAMP_IMAGE = CREATURE_INVENTORY_INDIVIDUAL_CREATURE_FAVORITE_STAMP_BASE + "_Favorite" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_INDIVIDUAL_CREATURE_NICKNAME_STAMP_IMAGE = CREATURE_INVENTORY_INDIVIDUAL_CREATURE_FAVORITE_STAMP_BASE + "_Nickname" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_INDIVIDUAL_CREATURE_MYTHICAL_STAMP_IMAGE = CREATURE_INVENTORY_INDIVIDUAL_CREATURE_FAVORITE_STAMP_BASE + "_Mythical" + IMAGE_FILE_EXTENSION

CREATURE_INVENTORY_RELEASE_SUMMARY_BG_IMAGE = CREATURE_INVENTORY_RELEASE_SUMMARY_BASE + "_Base" + IMAGE_FILE_EXTENSION
CREATURE_INVENTORY_RELEASE_SUMMARY_TAB_BG_IMAGE = CREATURE_INVENTORY_RELEASE_SUMMARY_BASE + "_TabBase" + IMAGE_FILE_EXTENSION
# endregion
# region Item Inventory images
ITEM_INVENTORY_BG_IMAGE = ITEM_INVENTORY_BASE + "BG" + IMAGE_FILE_EXTENSION
ITEM_INVENTORY_CORNER_OVERLAY_IMAGE = ITEM_INVENTORY_BASE + "CornerOverlay" + IMAGE_FILE_EXTENSION
ITEM_INVENTORY_TAB_BG_IMAGE = ITEM_INVENTORY_BASE + "TabBG" + IMAGE_FILE_EXTENSION
# endregion
# region Item Inventory Icons images
ITEM_INVENTORY_ICON_BAIT_IMAGE = ITEM_INVENTORY_ICON_BASE + "Bait" + IMAGE_FILE_EXTENSION
ITEM_INVENTORY_ICON_CHARM_IMAGE = ITEM_INVENTORY_ICON_BASE + "Charm" + IMAGE_FILE_EXTENSION
ITEM_INVENTORY_ICON_ANIMAL_IMAGE = ITEM_INVENTORY_ICON_BASE + "Animal" + IMAGE_FILE_EXTENSION
ITEM_INVENTORY_ICON_MISC_ITEM_IMAGE = ITEM_INVENTORY_ICON_BASE + "MiscItem" + IMAGE_FILE_EXTENSION
ITEM_INVENTORY_ICON_KEY_ITEM_IMAGE = ITEM_INVENTORY_ICON_BASE + "KeyItem" + IMAGE_FILE_EXTENSION

ITEM_INVENTORY_ICON_MEGAPHONE_IMAGE = ITEM_INVENTORY_ICON_BASE + "Megaphone" + IMAGE_FILE_EXTENSION
ITEM_INVENTORY_ICON_TRAP_IMAGE = ITEM_INVENTORY_ICON_BASE + "Trap" + IMAGE_FILE_EXTENSION
# endregion

# region Shop Paths
SHOP_BG_IMAGE = SHOP_BASE + "_BG" + IMAGE_FILE_EXTENSION
SHOP_CORNER_OVERLAY_IMAGE = SHOP_BASE + "_CornerOverlay" + IMAGE_FILE_EXTENSION
SHOP_CURRENCY_OVERLAY_IMAGE = SHOP_BASE + "_CurrencyOverlay" + IMAGE_FILE_EXTENSION

SHOP_MORSHU_OVERLAY_IMAGE = SHOP_BASE + "_MorshuOverlay" + IMAGE_FILE_EXTENSION
SHOP_TOP_SHELF_IMAGE = SHOP_SHELF_BASE + "_Top" + IMAGE_FILE_EXTENSION
SHOP_BOTTOM_SHELF_IMAGE = SHOP_SHELF_BASE + "_Bottom" + IMAGE_FILE_EXTENSION

SHOP_ITEM_CASE_IMAGE = SHOP_ITEM_CASE_BASE + IMAGE_FILE_EXTENSION
SHOP_TROPHY_CASE_IMAGE = SHOP_ITEM_CASE_BASE + "_Trophy" + IMAGE_FILE_EXTENSION
SHOP_ITEM_CASE_OVERLAY_IMAGE = SHOP_ITEM_CASE_BASE + "_Overlay" + IMAGE_FILE_EXTENSION
SHOP_ITEM_CASE_PRICE_TAG_IMAGE = SHOP_ITEM_CASE_BASE + "_PriceTag" + IMAGE_FILE_EXTENSION
SHOP_ITEM_CASE_SOLD_STICKER_IMAGE = SHOP_ITEM_CASE_BASE + "_SoldSticker" + IMAGE_FILE_EXTENSION

SHOP_UPDATE_RESTOCK_IMAGE = SHOP_UPDATE_BASE + "_Restock" + IMAGE_FILE_EXTENSION
SHOP_UPDATE_UPGRADE_IMAGE = SHOP_UPDATE_BASE + "_Upgrade" + IMAGE_FILE_EXTENSION

# endregion

# region Trap Manager Paths
TRAP_MANAGER_BG_IMAGE = TRAP_MANAGER_BASE + "_BG" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_CORNER_OVERLAY_IMAGE = TRAP_MANAGER_BASE + "_CornerOverlay" + IMAGE_FILE_EXTENSION

TRAP_MANAGER_CAPTURES_OVERLAY_IMAGE = TRAP_MANAGER_OVERLAY_CAPTURES_BASE + IMAGE_FILE_EXTENSION
TRAP_MANAGER_CAPTURES_ACTIVE_ARROW_LEFT_IMAGE = TRAP_MANAGER_OVERLAY_CAPTURES_BASE + "_ActiveArrow_L" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_CAPTURES_ACTIVE_ARROW_RIGHT_IMAGE = TRAP_MANAGER_OVERLAY_CAPTURES_BASE + "_ActiveArrow_R" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_CAPTURES_CREATURE_ICON_OVERLAY_IMAGE = TRAP_MANAGER_OVERLAY_CAPTURES_BASE + "_CreatureIcon_Overlay" + IMAGE_FILE_EXTENSION

TRAP_MANAGER_SUMMARY_OVERLAY_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_BASE + IMAGE_FILE_EXTENSION
TRAP_MANAGER_SUMMARY_BATTERY_BARS_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_BATTERY_BASE + "_Bars" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_SUMMARY_BATTERY_FULLY_CHARGED_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_BATTERY_BASE + "_Full" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_SUMMARY_BATTERY_ICON_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_BATTERY_BASE + "_Icon" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_SUMMARY_BATTERY_GLOW_ICON_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_BATTERY_BASE + "_Glow_Icon" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_SUMMARY_TRAP_MODE_OFF_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_TRAP_MODE_BASE + "_Off" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_SUMMARY_TRAP_MODE_ON_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_TRAP_MODE_BASE + "_On" + IMAGE_FILE_EXTENSION
TRAP_MANAGER_SUMMARY_TRAP_MODE_SCHEDULED_IMAGE = TRAP_MANAGER_OVERLAY_SUMMARY_TRAP_MODE_BASE + "_Scheduled" + IMAGE_FILE_EXTENSION
# endregion

# endregion


""" ----- EXTERNAL IMAGES  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
# region EXTERNAL IMAGES
# region catch creature embed icons
TGOMMO_CREATURE_EMBED_GRASS_ICON = "https://i.pinimg.com/originals/22/13/5b/22135b26441d0e9163eb4445af0c56c2.gif"
TGOMMO_CREATURE_EMBED_LOCATION_ICON = "https://cdn-icons-png.flaticon.com/512/535/535137.png"
# endregion
# endregion

""" ----- DEPRECATED  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
# region DEPRECATED
# region help menu images
HELP_IMAGE_BASE = os.path.join(IMAGE_FOLDER_HELP_IMAGE_PATH, "ExplanationCard_")

HELP_IMAGE_WELCOME_CARD = HELP_IMAGE_BASE + "HelpTitle" + IMAGE_FILE_EXTENSION
HELP_IMAGE_BUTTON_CARD = HELP_IMAGE_BASE + "Buttons" + IMAGE_FILE_EXTENSION
HELP_IMAGE_COMMAND_CARD_1 = HELP_IMAGE_BASE + "Commands1" + IMAGE_FILE_EXTENSION
HELP_IMAGE_COMMAND_CARD_2 = HELP_IMAGE_BASE + "Commands2" + IMAGE_FILE_EXTENSION
HELP_IMAGE_COMMAND_CARD_2_MYTHIC_ADDON = HELP_IMAGE_BASE + "Commands2_Mythical" + IMAGE_FILE_EXTENSION

HELP_IMAGE_WELCOME_CARD_INTRO = HELP_IMAGE_BASE + "IntroTitle" + IMAGE_FILE_EXTENSION
HELP_IMAGE_WELCOME_CARD_HOW_TO_PLAY = HELP_IMAGE_BASE + "HowToPlay" + IMAGE_FILE_EXTENSION
HELP_IMAGE_WELCOME_CARD_RARITY_SYSTEM = HELP_IMAGE_BASE + "RaritySystem" + IMAGE_FILE_EXTENSION
HELP_IMAGE_WELCOME_CARD_FUTURE_UPDATES = HELP_IMAGE_BASE + "FutureUpdates" + IMAGE_FILE_EXTENSION
# endregion
# endregion


""" --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
""" ----- FONTS  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""
FONTS_PATH = os.path.join(RESOURCES_FOLDER_BASE_PATH, "fonts")
FONT_FOREST_BOLD_FILE_TEMP = os.path.join(FONTS_PATH, "NationalForestPrintBold" + FONT_FILE_EXTENSION)
FONT_FOREST_REGULAR_FILE = os.path.join(FONTS_PATH, "NationalForestPrintRegular" + FONT_FILE_EXTENSION)
