import os
IMAGE_FILE_EXTENSION = ".png"
FONT_FILE_EXTENSION = ".otf"

'''Paths'''
RESOURCES_FOLDER_BASE_PATH = os.path.dirname(os.path.dirname(__file__))
IMAGE_FOLDER_IMAGES_PATH = RESOURCES_FOLDER_BASE_PATH + r"\images"
IMAGE_FOLDER_FONTS_PATH = RESOURCES_FOLDER_BASE_PATH + r"\fonts"

IMAGE_FOLDER_ENCYCLOPEDIA_PATH = IMAGE_FOLDER_IMAGES_PATH + r"\encyclopedia_resources"
IMAGE_FOLDER_HELP_IMAGE_PATH = IMAGE_FOLDER_IMAGES_PATH + r"\help_images"
IMAGE_FOLDER_DEX_ICON_PATH = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\dex_icons"
IMAGE_FOLDER_CREATURE_DEX_ICON_PATH = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\creature_icons"
IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\top_bar"
IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\bottom_bar"


'''Font Files'''
FONT_FOREST_BOLD_FILE_TEMP = IMAGE_FOLDER_FONTS_PATH + r"\NationalForestPrintBold" + FONT_FILE_EXTENSION
FONT_FOREST_REGULAR_FILE = IMAGE_FOLDER_FONTS_PATH + r"\NationalForestPrintRegular" + FONT_FILE_EXTENSION


'''ENCOUNTER SCREEN IMAGES'''
TEXT_BOX_IMAGE = IMAGE_FOLDER_IMAGES_PATH + r"\env_textbox" + IMAGE_FILE_EXTENSION


'''ENCYCLOPEDIA IMAGES'''
ENCYCLOPEDIA_CORNER_OVERLAY_BASE = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\EncyclopediaPage_CornerOverlay"
ENCYCLOPEDIA_BG_BASE = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\EncyclopediaPage_EnvironmentBG"

ENCYCLOPEDIA_OVERLAY_ROOT = IMAGE_FOLDER_ENCYCLOPEDIA_PATH + r"\EncyclopediaPage"

ENCYCLOPEDIA_OVERLAY_IMAGE = ENCYCLOPEDIA_OVERLAY_ROOT + r"_Overlay"+ IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_OVERLAY_SHINY_IMAGE = ENCYCLOPEDIA_OVERLAY_ROOT + r"_Overlay_SHINY"+ IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TEXT_SHADOW_IMAGE = ENCYCLOPEDIA_OVERLAY_ROOT + r"_Blackbar" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_CORNER_OVERLAY_SERVER_IMAGE = ENCYCLOPEDIA_OVERLAY_ROOT + r"_CornerOverlay_Server" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_CORNER_OVERLAY_USER_IMAGE = ENCYCLOPEDIA_OVERLAY_ROOT + r"_CornerOverlay_User" + IMAGE_FILE_EXTENSION

ENCYCLOPEDIA_BG_FOREST_1 = ENCYCLOPEDIA_BG_BASE + r"_1" + IMAGE_FILE_EXTENSION

'''TOP BAR FILES'''
ENCYCLOPEDIA_TOP_BAR_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH + r"\EncyclopediaPage_TopBar" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_SHINY_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH + r"\EncyclopediaPage_TopBar_Shiny" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_CAMERA_ICON_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH + r"\EncyclopediaPage_TopBar_CameraIcon" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_TOP_BAR_ENCOUNTER_ICON_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_TOP_BAR_PATH + r"\EncyclopediaPage_TopBar_EncounterIcon" + IMAGE_FILE_EXTENSION

'''BOTTOM BAR FILES'''
ENCYCLOPEDIA_BOTTOM_BAR_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH + r"\EncyclopediaPage_BottomBar" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BAR_SHINY_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH + r"\EncyclopediaPage_BottomBar_Shiny" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BACK_ARROW_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH + r"\EncyclopediaPage_BottomBar_Arrow_Backward" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_FORWARD_ARROW_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH + r"\EncyclopediaPage_BottomBar_Arrow_Forward" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_BACK_ARROW_IMAGE_DISABLED = IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH + r"\EncyclopediaPage_BottomBar_Arrow_Backward_Disabled" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_FORWARD_ARROW_IMAGE_DISABLED = IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH + r"\EncyclopediaPage_BottomBar_Arrow_Forward_Disabled" + IMAGE_FILE_EXTENSION
ENCYCLOPEDIA_BOTTOM_ENVIRONMENT_ICON_IMAGE = IMAGE_FOLDER_ENCYCLOPEDIA_BOTTOM_BAR_PATH + r"\EncyclopediaPage_BottomBar_EnvironmentIcon" + IMAGE_FILE_EXTENSION


'''DEX ICON FILES'''
DEX_ICON_BASE = IMAGE_FOLDER_DEX_ICON_PATH + r"\DexIcon"
DEX_ICON_BACKGROUND_BASE = DEX_ICON_BASE + "_BackgroundColor"
DEX_ICON_CREATURE_BASE = DEX_ICON_BASE + "_Creature"

DEX_ICON_CREATURE_LOCKED_ICON_IMAGE = DEX_ICON_CREATURE_BASE + "_LockedIcon" + IMAGE_FILE_EXTENSION
DEX_ICON_SHADOW_IMAGE = DEX_ICON_BASE + "_BGShadow" + IMAGE_FILE_EXTENSION
DEX_ICON_STATS_BAR_IMAGE = DEX_ICON_BASE + "_StatsBar" + IMAGE_FILE_EXTENSION
DEX_ICON_OVERLAY = DEX_ICON_BASE + "_Overlay" + IMAGE_FILE_EXTENSION


'''HELP IMAGE FILES'''
HELP_IMAGE_BASE = IMAGE_FOLDER_HELP_IMAGE_PATH + r"\ExplanationCard_"

HELP_IMAGE_WELCOME_CARD = HELP_IMAGE_BASE + r"HelpTitle" + IMAGE_FILE_EXTENSION
HELP_IMAGE_BUTTON_CARD = HELP_IMAGE_BASE + r"Buttons" + IMAGE_FILE_EXTENSION
HELP_IMAGE_COMMAND_CARD_1 = HELP_IMAGE_BASE + r"Commands1" + IMAGE_FILE_EXTENSION
HELP_IMAGE_COMMAND_CARD_2 = HELP_IMAGE_BASE + r"Commands2" + IMAGE_FILE_EXTENSION
HELP_IMAGE_COMMAND_CARD_2_MYTHIC_ADDON = HELP_IMAGE_BASE + r"Commands2_Mythical" + IMAGE_FILE_EXTENSION


'''CREATURE IMAGES'''
CREATURE_IMAGE_ENCOUNTER_EXTENSION = "_E"
CREATURE_IMAGE_FLEE_EXTENSION = "_F"
CREATURE_IMAGE_CATCH_EXTENSION = "_C"
CREATURE_IMAGE_THUMBNAIL_EXTENSION = "_THUMB"

CREATURE_IMAGE_CHIPMUNK_ROOT = "Chipmunk"
CREATURE_IMAGE_DEER_ROOT = "Deer"


'''EXTERNAL IMAGES'''
'''EMBED ICONS'''
TGOMMO_CREATURE_EMBED_GRASS_ICON = "https://i.pinimg.com/originals/22/13/5b/22135b26441d0e9163eb4445af0c56c2.gif"
TGOMMO_CREATURE_EMBED_LOCATION_ICON = "https://cdn-icons-png.flaticon.com/512/535/535137.png"