'''TGO MMO'''
N00_BASE_CREATURE_IMAGE_FILE = "BASE_CREATURE.png"
N00_BASE_CREATURE_IMAGE_FILE_ENCOUNTER = "BASE_CREATURE_E.png"
N00_BASE_CREATURE_IMAGE_FILE_FLEE = "BASE_CREATURE_F.png"
N00_BASE_CREATURE_IMAGE_FILE_CATCH = "BASE_CREATURE_C.png"
N00_BASE_CREATURE_IMAGE_FILE_THUMBNAIL = "BASE_CREATURE_THUMB.png"


N01_CHIPMUNK_IMAGE_FILE = "01_Chipmunk_O"
N02_DOE_IMAGE_FILE = "01_Chipmunk_O.png"
